name: Update Wiki

# Controls when the workflow will run
on:
  # Triggers the workflow on push that edits the wiki contents
  push:
    branches: [ "main" ]
    paths:
      - '.github/wiki/**'
  
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update Wiki

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # NOTE: @main so I can dogfood the latest version, but you'll probably want to use a tag
      # See https://github.com/spenserblack/actions-wiki/tags
      - uses: spenserblack/actions-wiki@main
        with:
          token: ${{ secrets.WIKI_TOKEN }}
